16:50:18.641 TRACE [17142] [BROKER] ffbroker_t::open accept ok<tcp://127.0.0.1:10241>
16:50:18.641 TRACE [17142] [FFGATE] ffgate_t::open begin broker<tcp://127.0.0.1:10241>
16:50:18.641 INFO  [17142] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::handle_msg_impl cmd<3> begin
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::handle_client_register begin
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::handle_client_register alloc node id<1>,binder_broker[0]
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::sync_all_register_info begin
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::sync_all_register_info to node_id[1]
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::sync_all_register_info end ok
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::handle_client_register end ok
16:50:18.642 TRACE [17142] [BROKER] ffbroker_t::handle_msg_impl cmd<3> end ok
16:50:18.642 TRACE [17142] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[1] begin
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::gate_broadcast_msg_to_session_t::in_t] -> msg id[2]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::gate_change_logic_node_t::in_t] -> msg id[3]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::gate_close_session_t::in_t] -> msg id[4]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::gate_route_msg_to_session_t::in_t] -> msg id[5]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::open end ok m_node_id[1]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
16:50:18.643 TRACE [17142] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
16:50:18.643 TRACE [17142] [FFGATE] ffgate_t::open end ok
16:50:18.668 TRACE [17142] [FFSCENE_PYTHON] ffscene_python_t::open begin
16:50:18.680 ERROR [17142] [DB_MGR] db_mgr_t::connect_db failed<Access denied for user 'root'@'localhost' (using password: YES)>
