21:46:39.065 TRACE [32715] [FFSCENE_PYTHON] ffscene_python_t::open begin
21:46:39.300 TRACE [32715] [FFSCENE] ffscene_t::open begin
21:46:39.300 INFO  [32715] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
21:46:39.300 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:46:39.300 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[6] begin
21:46:39.300 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::open end ok m_node_id[6]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[6],bind_broker_id[0]
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:46:39.301 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:46:39.301 TRACE [32715] [FFSCENE] ffscene_t::open end ok
21:46:39.301 TRACE [32715] [FFSCENE_PYTHON] ffscene_python_t::open end ok
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[0] begin
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[6],bind_broker_id[0]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[12],bind_broker_id[0]
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:46:39.311 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:46:45.652 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:46:45.652 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[1] begin
21:46:45.652 TRACE [32715] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:46:45.701 ERROR [32715] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<value returned is not vector ff_session_verify in ffext>
21:46:45.701 TRACE [32715] [FFSCENE] ffscene_t::process_session_verify end ok
21:46:45.701 INFO  [32715] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:46:45.701 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:46:45.701 INFO  [32715] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:46:45.702 TRACE [32715] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[1] end ok
21:46:58.956 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:46:58.956 TRACE [32715] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[2] begin
21:46:58.956 TRACE [32715] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:46:58.957 ERROR [32715] [DB_MGR] db_mgr_t::sync_db_query failed<Duplicate entry 'pascal' for key 'PRIMARY'>, while sql<INSERT INTO `account` (`ACCOUNT_ID`, `SESSION_ID`, `SESSION_UPD_TIME`, `CREATE_DATA`) VALUES ('pascal', '4360573305', now(), now()) >
21:46:58.958 ERROR [32715] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 94, in ff_session_verify
    ret = g_session_verify_callback(session_key, online_time, ip, gate_name)

  File "./pyproject/player_mgr/player_mgr_handler.py", line 11, in real_session_verify
    session_id = dbservice.get_session_by_auth_key(szAuthKey)

  File "./pyproject/db/dbservice.py", line 38, in get_session_by_auth_key
    assert ret.flag is True

AssertionError

>
21:46:58.958 TRACE [32715] [FFSCENE] ffscene_t::process_session_verify end ok
21:46:58.958 INFO  [32715] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:46:58.958 TRACE [32715] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:46:58.958 INFO  [32715] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:46:58.958 TRACE [32715] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[2] end ok
