21:37:28.075 TRACE [31983] [FFSCENE_PYTHON] ffscene_python_t::open begin
21:37:28.311 TRACE [31983] [FFSCENE] ffscene_t::open begin
21:37:28.311 INFO  [31983] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
21:37:28.312 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:37:28.312 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[6] begin
21:37:28.312 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:37:28.312 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[6],bind_broker_id[0]
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:37:28.313 TRACE [31983] [FFRPC] ffrpc_t::open end ok m_node_id[6]
21:37:28.313 TRACE [31983] [FFSCENE] ffscene_t::open end ok
21:37:28.313 TRACE [31983] [FFSCENE_PYTHON] ffscene_python_t::open end ok
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[0] begin
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[6],bind_broker_id[0]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[12],bind_broker_id[0]
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:37:28.325 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:39:10.447 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:39:10.447 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[1] begin
21:39:10.447 TRACE [31983] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:39:10.450 ERROR [31983] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<list index out of range
Traceback (most recent call last):

  File "./pylib/ffext.py", line 94, in ff_session_verify
    ret = g_session_verify_callback(session_key, online_time, ip, gate_name)

  File "./pyproject/player_mgr/player_mgr_handler.py", line 11, in real_session_verify
    session_id = dbservice.get_session_by_auth_key(szAuthKey)

  File "./pyproject/db/dbservice.py", line 37, in get_session_by_auth_key
    return int(ret.result[0][0])

IndexError: list index out of range

>
21:39:10.451 TRACE [31983] [FFSCENE] ffscene_t::process_session_verify end ok
21:39:10.451 INFO  [31983] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:39:10.451 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:39:10.451 INFO  [31983] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:39:10.451 TRACE [31983] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[1] end ok
21:39:20.694 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:39:20.694 TRACE [31983] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[2] begin
21:39:20.694 TRACE [31983] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:39:20.696 ERROR [31983] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<list index out of range
Traceback (most recent call last):

  File "./pylib/ffext.py", line 94, in ff_session_verify
    ret = g_session_verify_callback(session_key, online_time, ip, gate_name)

  File "./pyproject/player_mgr/player_mgr_handler.py", line 11, in real_session_verify
    session_id = dbservice.get_session_by_auth_key(szAuthKey)

  File "./pyproject/db/dbservice.py", line 37, in get_session_by_auth_key
    return int(ret.result[0][0])

IndexError: list index out of range

>
21:39:20.696 TRACE [31983] [FFSCENE] ffscene_t::process_session_verify end ok
21:39:20.696 INFO  [31983] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:39:20.696 TRACE [31983] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:39:20.696 INFO  [31983] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:39:20.696 TRACE [31983] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[2] end ok
